archetypes:  # `caf-enterprise-scale` module, add inputs as listed on the module registry where necessary.
  # Base variables
  root_name: Soniak
  root_id: soniak-alz
  subscription_id_connectivity: ${subscription_id_connectivity}
  subscription_id_identity: ${subscription_id_identity}
  subscription_id_management: ${subscription_id_management}
  root_parent_id: ${root_parent_management_group_id}
  deploy_core_landing_zones: true
  deploy_corp_landing_zones: true
  deploy_online_landing_zones: true
  default_location: ${default_location}
  deploy_management_resources: true
  deploy_connectivity_resources: true
  deploy_identity_resources: true
  disable_telemetry: true


connectivity:
  hubnetworking:  # `hubnetworking` module, add inputs as listed on the module registry where necessary.
    hub_virtual_networks:
      primary:
        name: vnet-hub-uks
        resource_group_name: rg-connectivity-uks
        location: ${default_location}
        address_space:
          - 10.0.0.0/16
        firewall:
          name: fw-hub
          sku_name: AZFW_VNet
          sku_tier: Standard
          subnet_address_prefix: 10.0.0.0/24
        mesh_peering_enabled: true
        virtual_network_gateway:  # `vnet-gateway` module, add inputs as listed on the module registry where necessary.
          name: vgw-hub-uks
          sku: VpnGw1
          type: Vpn
          subnet_address_prefix: 10.0.2.0/24
      secondary:
        name: vnet-hub-ukw
        resource_group_name: rg-connectivity-ukw
        location: ukwest
        address_space:
          - 10.1.0.0/16
        firewall:
          name: fw-hub-ukw  # Adjusted the name to match the network for clarity
          sku_name: AZFW_VNet
          sku_tier: Standard
          subnet_address_prefix: 10.1.1.0/24  # Adjusted to match the description
        mesh_peering_enabled: true
        virtual_network_gateway:  # `vnet-gateway` module, add inputs as listed on the module registry where necessary.
          name: vgw-hub-ukw
          sku: VpnGw1
          type: Vpn
          subnet_address_prefix: 10.1.2.0/24




